version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
  torproxy:
    image: dperson/torproxy
    ports:
      - "8118:8118"
      - "9050:9050"
